java_binary(
    name = "ladder",
    srcs = ["Ladder.java"],
    main_class = "me.rsole.ladder.Ladder",
    data = ["//third_party/data:words"],
    deps = [
        "//java/me/rsole/graph:graph",
        "@com_google_guava_guava//jar"
    ],
)
